/**
 * WordPress dependencies
 */
const defaultConfig = require( '@wordpress/scripts/config/webpack.config' );

/**
 * External dependencies
 */
const RemoveEmptyScriptsPlugin = require( 'webpack-remove-empty-scripts' );
const path = require( 'path' );

// Extend the default webpack config.
module.exports = {
	...defaultConfig,
	output: {
		...defaultConfig.output,
		path: path.resolve( process.cwd(), 'build-scripts' ),
	},
	entry: {
		...defaultConfig.entry(),
		'admin/settings': path.resolve(
			process.cwd(),
			'src/admin/settings',
			'index.scss'
		),
		'experiments/content-classification': path.resolve(
			process.cwd(),
			'src/experiments/content-classification',
			'index.tsx'
		),
		'experiments/abilities-explorer': path.resolve(
			process.cwd(),
			'src/experiments/abilities-explorer',
			'index.js'
		),
		'experiments/example-experiment': path.resolve(
			process.cwd(),
			'src/experiments/example-experiment',
			'index.tsx'
		),
		'experiments/excerpt-generation': path.resolve(
			process.cwd(),
			'src/experiments/excerpt-generation',
			'index.tsx'
		),
		'experiments/image-generation': path.resolve(
			process.cwd(),
			'src/experiments/image-generation',
			'index.ts'
		),
		'experiments/meta-description': path.resolve(
			process.cwd(),
			'src/experiments/meta-description',
			'index.tsx'
		),
		'experiments/review-notes': path.resolve(
			process.cwd(),
			'src/experiments/review-notes',
			'index.tsx'
		),
		'experiments/summarization': path.resolve(
			process.cwd(),
			'src/experiments/summarization',
			'index.tsx'
		),
		'experiments/title-generation': path.resolve(
			process.cwd(),
			'src/experiments/title-generation',
			'index.tsx'
		),
		'experiments/alt-text-generation': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'index.tsx'
		),
		'experiments/content-provenance': path.resolve(
			process.cwd(),
			'src/experiments/content-provenance',
			'index.js'
		),
		'experiments/alt-text-generation-media': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'media.ts'
		),
		'experiments/alt-text-generation-bulk': path.resolve(
			process.cwd(),
			'src/experiments/alt-text-generation',
			'bulk.ts'
		),
	},

	plugins: [
		// Include WP's plugin config.
		...defaultConfig.plugins,

		// Removes the empty `.js` files generated by webpack but
		// sets it after WP has generated its `*.asset.php` file.
		new RemoveEmptyScriptsPlugin( {
			stage: RemoveEmptyScriptsPlugin.STAGE_AFTER_PROCESS_PLUGINS,
		} ),
	],
};
